### ISSUE TITLE
All base boxes

### ISSUE THREAD

**Issue by elreydetoda** [ProfessionallyEvil/PENT#1]
## Linux
- [ ] metasploitable1 - #2 
- [ ] metasploitable2 - #3 
- [ ] metasploitable3 - #4 
- [ ] samurai vuln websites - #5 

## Windows
- [ ] parent domain core 2k12r2 - #6 
- [ ] child domain core 2k12r2 - #6 
- [ ] metasploitable3 2k12 - #4 

### script to automate
- [ ] builds all the vms #7 
- [ ] script that uploads all the vms to vagrant cloud w/version #7 
- [ ] tag version (i.e. 1) for the code
